jms_serializer:
    handlers:
        datetime:
            default_format: 'Y-m-d H:i:s'
            default_timezone: 'UTC'
    metadata:
        auto_detection: true

when@prod:
    jms_serializer:
        visitors:
        xml_serialization:
            format_output: '%kernel.debug%'
        json_serialization:
            options: [JSON_PRETTY_PRINT, JSON_UNESCAPED_SLASHES]
    property_naming:
        id: 'jms_serializer.identical_property_naming_strategy'

when@dev:
    jms_serializer:
        visitors:
            json_serialization:
                options:
                    - JSON_PRETTY_PRINT
                    - JSON_UNESCAPED_SLASHES
                    - JSON_PRESERVE_ZERO_FRACTION
